"""Amazon-Reviews 2023 Musical_Instruments dataset adapter for RQ-VAE-Recommender.

Post-Refactor (2026-09-23): every input now flows from stage0/stage1 outputs
rather than from a self-contained ``dataset/Instruments`` snapshot:

- user-event splits: ``results/stage0_build_parquet/{train,valid,test}.parquet``
- item embeddings:  ``stage1_GeneEmbedding/output/sentence_t5.npy``
                    (24587, 768) float32, row order = sorted item_id
- item metadata:    ``results/stage0_build_parquet/items.parquet``
- item id ordering: ``stage1_GeneEmbedding/output/item_ids.json`` (sidecar)

The constants below pin these paths; no env / CLI / argparse override
(CLAUDE.md §1).
"""
import json
import os
import os.path as osp
from typing import Callable, List, Optional

import numpy as np
import pandas as pd
import polars as pl
import torch
from torch_geometric.data import HeteroData, InMemoryDataset


# === Stage 0 / Stage 1 路径 (CLAUDE.md §1, no env/CLI override) ===
DATASET_ROOT    = "/home/wlia0047/ar57/wenyu/GeneRec/dataset"  # raw JSON lives here
STAGE0_DIR      = "/home/wlia0047/ar57/wenyu/GeneRec/results/stage0_build_parquet"
STAGE1_OUT_DIR  = "/home/wlia0047/ar57/wenyu/GeneRec/stage1_GeneEmbedding/output"
ITEM_EMB_NPY    = f"{STAGE1_OUT_DIR}/sentence_t5.npy"     # stage1 output
ITEM_IDS_JSON   = f"{STAGE1_OUT_DIR}/item_ids.json"       # stage1 sidecar row order
TRAIN_PARQUET   = f"{STAGE0_DIR}/train.parquet"           # stage0 user-event split
VALID_PARQUET   = f"{STAGE0_DIR}/valid.parquet"
TEST_PARQUET    = f"{STAGE0_DIR}/test.parquet"

# Amazon 一样的 max_seq_len (因为 seq_data 内部会切前 max_seq_len 个)
MAX_SEQ_LEN = 20


class RawMusicalInstruments(InMemoryDataset):
    """Amazon-Reviews 2023 Musical_Instruments dataset (post-Refactor).

    Item count is read from stage0's ``items.parquet`` (24587 today) and
    user count from ``train.parquet``; downstream code only relies on the
    row order, so this class is dataset-size agnostic.

    Raw 输入 (post-Refactor):
      - ``results/stage0_build_parquet/{train,valid,test}.parquet`` with cols
        ``[user, history, seen_history, target]`` (leave-one-out 三段切分, history 累积)
      - ``stage1_GeneEmbedding/output/sentence_t5.npy`` — (N, 768) sentence-t5 emb
      - ``stage1_GeneEmbedding/output/item_ids.json`` — row-i → item_id mapping
      - ``results/stage0_build_parquet/items.parquet`` — title/description per item

    Processed 输出 (HeteroData):
      data["item"].x: (N, 768) sentence-t5 embedding
      data["item"].text: (N,) "title. description[:512]" per item
      data["item"].is_train: (N,) 全 True (所有 instrument 都参与 embedding 学习)
      data[("user", "rated", "item")].history: {train/eval/test} 三个 split
        - train.itemId: list[list[int]] 各用户历史 items (可变长度, 训时随机切片)
        - train.itemId_fut: list[int] 下一 item (倒数第二)
        - eval.itemId: padded (max_seq_len,) 用于 eval
        - eval.itemId_fut: list[int] 倒数第二
        - test.itemId: padded (max_seq_len,) 用于 eval
        - test.itemId_fut: list[int] 最后一个
    """

    def __init__(
        self,
        root: str,
        split: str = "instruments",  # 占位用, 实际不用 split 区分 (只有一个 split)
        transform: Optional[Callable] = None,
        pre_transform: Optional[Callable] = None,
        force_reload: bool = False,
    ) -> None:
        self.split = split
        # InMemoryDataset 需要 processed_paths, 我们设到 root/processed/data_instruments.pt
        super().__init__(root, transform, pre_transform, force_reload)
        self.load(self.processed_paths[0], data_cls=HeteroData)

    @property
    def raw_dir(self) -> str:
        # override: stage0 writes train/valid/test.parquet here (post-Refactor).
        return STAGE0_DIR

    @property
    def processed_dir(self) -> str:
        # override: 写到 results/stage2_RQ-VAE/curvature_RQ-VAE/processed 内部,
        # 跟其他 stage 输出都在 results/ 下. (历史写在 hj82_scratch2 是为了避开
        # /home 20G 限制, 现在 results 已经是 fs04 大盘, 5G+ 都没问题.)
        return "/home/wlia0047/ar57/wenyu/GeneRec/results/stage2_RQ-VAE/curvature_RQ-VAE/processed"

    @property
    def raw_file_names(self) -> List[str]:
        # stage0 output names (post-Refactor).  ``Instruments.item.json``
        # is no longer required (item metadata flows via items.parquet -> stage1
        # sentence_t5.npy; only the user-event splits live in this directory).
        return ["train.parquet", "valid.parquet", "test.parquet"]

    @property
    def processed_file_names(self) -> str:
        return f"data_{self.split}.pt"

    def download(self) -> None:
        # No-op: 数据已就绪 (R44 约束)
        pass

    def _build_sequences(self, max_seq_len: int = MAX_SEQ_LEN):
        """从 train/valid/test.parquet 构造序列 split.

        Post-Refactor contract (matches stage0's RecBole TIGER prefix-expanded
        schema -- generated by ``stage0_build_parquet/build_recbole_parquet.py``):

        - ``train.parquet`` is **prefix-expanded**: one row per (user, prefix)
          combination.  ``history[i]`` is the user's cumulative item list up
          to but not including ``target``.  Stage0 keeps it in user-iteration
          order so groupby+sort preserves the temporal chain.
        - ``valid.parquet`` / ``test.parquet``: one row per user with
          ``history = user[:i]`` and ``target = user[i]`` for the
          ``i = len-2 / len-1`` holdouts.

        Per user we rebuild the full temporal asin sequence by reading each
        (history, target) train prefix pair (the new target extends the prior
        history).  The result matches RecBole's ``raw_seq`` layout exactly,
        so the train/eval/test split math below is unchanged from the
        original implementation.

        Item-id indexing: stage0 writes raw asin integers straight from the
        source dump (``Instruments.inter.json`` parses as string IDs, then
        they are cast to ``int64`` for parquet).  The original code subtracted
        1 to convert from a 1-indexed Amazon Reviews convention; we drop
        that mapping because our parquet is already 0-indexed.  Padding
        remains at -1.
        """
        train_df = pd.read_parquet(TRAIN_PARQUET).sort_values("user", kind="stable")
        # The ``history`` column holds per-row numpy arrays which pandas
        # cannot sort on; ``target`` sort would scramble the prefix order.
        # Groupby(sort=False) below preserves stage0's row order, which is
        # the prefix-expansion chain.
        valid_df = pd.read_parquet(VALID_PARQUET).set_index("user")
        test_df  = pd.read_parquet(TEST_PARQUET ).set_index("user")

        sequences = {sp: {"userId": [], "itemId": [], "itemId_fut": []} for sp in ["train", "eval", "test"]}

        for user_id, group in train_df.groupby("user", sort=False):
            # stage0 rows are kept in prefix-expansion order within a user,
            # so ``group["target"].tolist()`` already is the temporal chain
            # of (target_1, target_2, ...) without any reconstruction.
            t_train = [int(t) for t in group["target"].tolist()]
            if user_id not in valid_df.index or user_id not in test_df.index:
                continue
            t_valid = int(valid_df.loc[user_id, "target"])
            t_test  = int(test_df .loc[user_id, "target"])

            raw_seq = t_train + [t_valid, t_test]

            train_items = raw_seq[:-3]
            sequences["train"]["userId"].append(int(user_id))
            sequences["train"]["itemId"].append(train_items)
            sequences["train"]["itemId_fut"].append(t_train[-1] if t_train else -1)

            eval_items = raw_seq[-(max_seq_len + 2):-2]
            if len(eval_items) < max_seq_len:
                eval_items = [-1] * (max_seq_len - len(eval_items)) + eval_items
            sequences["eval"]["userId"].append(int(user_id))
            sequences["eval"]["itemId"].append(eval_items)
            sequences["eval"]["itemId_fut"].append(t_valid)

            test_items = raw_seq[-(max_seq_len + 1):-1]
            if len(test_items) < max_seq_len:
                test_items = [-1] * (max_seq_len - len(test_items)) + test_items
            sequences["test"]["userId"].append(int(user_id))
            sequences["test"]["itemId"].append(test_items)
            sequences["test"]["itemId_fut"].append(t_test)

        # 转 polars DataFrame (与 Amazon 风格一致)
        for sp in sequences:
            sequences[sp] = pl.from_dict(sequences[sp])

        return sequences

    def process(self, max_seq_len: int = MAX_SEQ_LEN) -> None:
        from data.preprocessing import PreprocessingMixin
        data = HeteroData()

        # --- 1. user sequences ---
        sequences = self._build_sequences(max_seq_len=max_seq_len)
        history_dict = {}
        for sp, df in sequences.items():
            # 走 PreprocessingMixin._df_to_tensor_dict 与 Amazon 完全一致:
            #   变长 itemId 保持 list[list[int]], 定长 itemId_fut/userId 转 tensor
            tensor_dict = PreprocessingMixin._df_to_tensor_dict(df, ["itemId"])
            history_dict[sp] = tensor_dict
        data["user", "rated", "item"].history = history_dict

        # --- 2. item features (post-Refactor: 完全从 stage0 + stage1 读) ---
        # 2a. embedding: stage1 sentence_t5.npy, row order = sorted(item_id)
        item_emb = torch.from_numpy(np.load(ITEM_EMB_NPY).astype(np.float32))
        if item_emb.ndim != 2 or item_emb.shape[1] != 768:
            raise ValueError(
                f"stage1 sentence_t5.npy shape must be (N, 768), got {item_emb.shape}"
            )

        # 2b. item-id ordering: 从 stage1 sidecar item_ids.json 确认行序
        with open(ITEM_IDS_JSON, "r") as handle:
            item_ids_emb_order = [int(v) for v in json.load(handle)]

        # 2c. text: 从 stage0 的 items.parquet 取 (title/description 已规范化)
        items_df = pd.read_parquet(os.path.join(STAGE0_DIR, "items.parquet"))
        items_df = items_df.set_index("item_id").reindex(item_ids_emb_order)
        texts = []
        for iid in item_ids_emb_order:
            row = items_df.loc[iid]
            def _str(field):
                v = row[field]
                if pd.isna(v):
                    return ""
                if isinstance(v, list):
                    return ", ".join(str(x) for x in v if x)
                return str(v)
            title = _str("title").strip()
            desc = _str("description").strip()[:512]
            text = f"{title}. {desc}".strip(". ")
            if not text:
                text = "(no description)"
            texts.append(text)

        data["item"].x = item_emb
        data["item"].text = np.array(texts)
        data["item"].is_train = torch.ones(item_emb.shape[0], dtype=torch.bool)

        # 存 processed
        os.makedirs(self.processed_dir, exist_ok=True)
        self.save([data], self.processed_paths[0])
        print(f"[instruments] processed → {self.processed_paths[0]}", flush=True)
        print(f"  users={len(sequences['train']['userId'])}, items={item_emb.shape[0]}", flush=True)
        for sp in ["train", "eval", "test"]:
            n = len(sequences[sp]["userId"])
            print(f"  split={sp}: {n} users", flush=True)


# =============================================================================
# HG-Rec 架构兼容层 (C33 Issue #181 合并):
# 把 per-hierarchy CE 路径 (EncoderDecoderRetrievalModel + SemanticIdTokenizer)
# 切到序列级 CE 路径 (HG_Rec + GenRecDataset + flat token sequence)
# 复用同一份 Instruments parquet, 仅数据预处理格式不同
# =============================================================================

def _hgrec_pad_or_truncate(sequence, max_len, PAD_TOKEN=0):
    """HG-Rec 风格: 截断 / 左填充 PAD."""
    if len(sequence) > max_len:
        return sequence[-max_len:]
    return [PAD_TOKEN] * (max_len - len(sequence)) + sequence


def _hgrec_process_data(file_path, mode, max_len, PAD_TOKEN=0):
    """读 parquet → 转 HG-Rec 格式 dict-of-list (history 与 target 为 list[int]).

    mode='train': 每个用户产生多个 (history, target) pair (前向滑动切片)
    mode='evaluation': 每个用户仅 1 个 pair (history[:-1], target=sequence[-1])
    """
    data = pd.read_parquet(file_path)
    data['sequence'] = data['history'].apply(lambda x: list(x)) + data['target'].apply(lambda x: [x])
    processed = []
    if mode == 'train':
        for row in data.itertuples(index=False):
            seq = row.sequence
            for i in range(1, len(seq)):
                processed.append({"history": seq[:i], "target": seq[i]})
    elif mode == 'evaluation':
        for row in data.itertuples(index=False):
            seq = row.sequence
            processed.append({"history": seq[:-1], "target": seq[-1]})
    else:
        raise ValueError(f"Mode must be 'train' or 'evaluation', got {mode!r}")
    for item in processed:
        item['history'] = _hgrec_pad_or_truncate(item['history'], max_len, PAD_TOKEN)
    return processed


def _hgrec_item2code(code_path, codebook_size):
    """读 (N, 3) SID numpy → dict {item_id_1indexed: (4,) vocab id list}.

    HG-Rec vocab 平铺: layer l 的 code c → vocab_id = 1 + sum(codebook_size[0:l]) + c
    第 4 层 (codebook_size=[1]) 保持 0 (PAD).

    C33 patch: HG-Rec 原版 vocab_size=1025 (4 层 codebook_size=[256,256,256,1]).
    C28 只有 3 层, 第 4 位填 PAD=0. 直接保留 0, 不加 offset, 避免越界 vocab_size=769.

    R36c fix v87: sids shape=(N, 3), 但 item_to_code 必须返回 4-token list (与 history target 对齐).
    否则 collate_fn flatten 后 token 数 4*N vs 4*N+3 不等, stack 失败.
    """
    sids = np.load(code_path, allow_pickle=True)
    item_to_code = {}
    for idx, code in enumerate(sids):
        offsets = []
        for i, c in enumerate(code):
            if i >= len(codebook_size) or codebook_size[i] == 1:
                offsets.append(0)  # R36c fix: PAD, not raw c
            else:
                offsets.append(int(c) + sum(codebook_size[0:i]) + 1)
        # R36c fix v87: 强制补 PAD 到 4-token (与历史 baseline 4 层对齐)
        while len(offsets) < 4:
            offsets.append(0)
        item_to_code[idx + 1] = offsets  # item_id 1-indexed (与 parquet 一致)
    return item_to_code


class GenRecDataset(torch.utils.data.Dataset):
    """HG-Rec 序列数据集: 输出 {history: [(item_code, 4)×max_len], target: (item_code, 4)}."""

    def __init__(self, parquet_path, code_path, mode, codebook_size, max_len, PAD_TOKEN=0):
        self.parquet_path = parquet_path
        self.code_path = code_path
        self.mode = mode
        self.max_len = max_len
        self.PAD_TOKEN = PAD_TOKEN
        self.codebook_size = codebook_size
        self.item_to_code = _hgrec_item2code(code_path, codebook_size)
        self.data = self._prepare_data()

    def _prepare_data(self):
        processed = _hgrec_process_data(self.parquet_path, self.mode, self.max_len, self.PAD_TOKEN)
        pad_code = [self.PAD_TOKEN] * 4
        for item in processed:
            item['history'] = [self.item_to_code.get(int(x), pad_code) for x in item['history']]
            item['target'] = self.item_to_code.get(int(item['target']), pad_code)
        return processed

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return len(self.data)


def hgrec_collate_fn(batch, pad_token=0):
    """HG-Rec collate: history (B, max_len, 4) → flat (B, max_len*4), target (B, 4).

    R36c fix v87: 不同 sample 的 history 长度不同 (< max_len), 必须 pad 到 batch 内 max_len,
    否则 torch.stack 失败 "got [N] at entry 0 and [M] at entry 1".
    """
    max_h = max(len(item['history']) for item in batch)
    pad_code = [pad_token] * 4
    flat_histories = torch.stack([
        torch.tensor(
            [tok for codes in (item['history'] + [pad_code] * (max_h - len(item['history'])))
             for tok in codes],
            dtype=torch.int64,
        )
        for item in batch
    ])
    targets = torch.stack([torch.tensor(item['target'], dtype=torch.int64) for item in batch])
    attn = torch.stack([
        torch.tensor([1 if tok != pad_token else 0 for tok in h], dtype=torch.int64)
        for h in flat_histories
    ])
    return {"history": flat_histories, "target": targets, "attention_mask": attn}


class RawMusicalInstrumentsHGRec:
    """HG-Rec 风格 Musical_Instruments 数据集包装器.

    不依赖 HeteroData/SemanticIdTokenizer, 直接读 parquet + SID numpy.

    用法:
        train_ds = RawMusicalInstrumentsHGRec(
            parquet_path="/.../train.parquet",
            code_path="/.../Instruments_c28_sids_for_hgrec.npy",
            mode="train",
            codebook_size=[256, 256, 256],
            max_len=20,
        )
        loader = DataLoader(train_ds, batch_size=256, shuffle=True,
                            collate_fn=hgrec_collate_fn, num_workers=2)
    """

    def __init__(self, parquet_path, code_path, mode, codebook_size, max_len, PAD_TOKEN=0):
        self.dataset = GenRecDataset(
            parquet_path=parquet_path,
            code_path=code_path,
            mode=mode,
            codebook_size=codebook_size,
            max_len=max_len,
            PAD_TOKEN=PAD_TOKEN,
        )

    def __getitem__(self, index):
        return self.dataset[index]

    def __len__(self):
        return len(self.dataset)
